Correct number of arguments when raising TransportableException
When using joblib for parallel processing, errors can cause a confusing stack:
```
File "python2.7/site-packages/joblib/parallel.py", line 651, in __call__
    self.retrieve()
  File "lib/python2.7/site-packages/joblib/parallel.py", line 534, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```
TransportableExceptions take both the message and message type:

https://github.com/joblib/joblib/blob/001fab4ab42e604a5471a6bef9722ea3d77e4309/joblib/my_exceptions.py#L41

and this small change fixes it.